<?php
class Order extends Model
{
    public function createFromCart(array $d): int { $cart=new Cart(); $items=$cart->items(); if(!$items) throw new RuntimeException('السلة فارغة'); $tot=$cart->totals(); if($tot['subtotal'] < $tot['min_order']) throw new RuntimeException('الطلب أقل من الحد الأدنى'); $this->db->beginTransaction(); try{ $number=$this->number(); $this->db->prepare('INSERT INTO orders(order_number,user_id,session_id,customer_name,customer_phone,customer_address,customer_city,notes,subtotal,delivery_fee,total) VALUES(?,?,?,?,?,?,?,?,?,?,?)')->execute([$number,current_user()['id']??null,current_user()?null:$cart->sessionId(),$d['customer_name'],$d['customer_phone'],$d['customer_address'],$d['customer_city'],$d['notes']??null,$tot['subtotal'],$tot['delivery_fee'],$tot['total']]); $oid=(int)$this->db->lastInsertId(); $st=$this->db->prepare('INSERT INTO order_items(order_id,product_id,variant_id,weight_grams,quantity,unit_price,line_total,product_name,variant_name,is_weight_based) VALUES(?,?,?,?,?,?,?,?,?,?)'); foreach($items as $i){ $st->execute([$oid,$i['product_id'],$i['variant_id'],$i['weight_grams'],$i['quantity'],$i['unit_price'],$i['unit_price']*$i['quantity'],$i['product_name'],$i['variant_name'],$i['is_weight_based']]); $this->deduct($i); } $this->db->prepare('UPDATE orders SET stock_deducted=1 WHERE id=?')->execute([$oid]); $cart->clear(); $this->db->commit(); return $oid; } catch(Throwable $e){$this->db->rollBack(); throw $e;} }
    private function number(): string { $prefix='SH-'.date('ymd').'-'; $st=$this->db->prepare('SELECT COUNT(*) FROM orders WHERE DATE(created_at)=CURDATE()'); $st->execute(); return $prefix.str_pad(((int)$st->fetchColumn())+1,4,'0',STR_PAD_LEFT); }
    private function deduct(array $i): void { if($i['variant_id']) $this->db->prepare('UPDATE product_variants SET stock=GREATEST(stock-?,0) WHERE id=?')->execute([$i['quantity'],$i['variant_id']]); elseif($i['is_weight_based'] && $i['weight_grams']) $this->db->prepare('UPDATE products SET stock=GREATEST(stock-?,0) WHERE id=?')->execute([ceil($i['weight_grams']*$i['quantity']/1000),$i['product_id']]); else $this->db->prepare('UPDATE products SET stock=GREATEST(stock-?,0) WHERE id=?')->execute([$i['quantity'],$i['product_id']]); }
    public function find(int $id): ?array { $st=$this->db->prepare('SELECT * FROM orders WHERE id=?'); $st->execute([$id]); return $st->fetch() ?: null; }
    public function items(int $id): array { $st=$this->db->prepare('SELECT * FROM order_items WHERE order_id=?'); $st->execute([$id]); return $st->fetchAll(); }
    public function mine(): array { if(!current_user()) return []; $st=$this->db->prepare('SELECT * FROM orders WHERE user_id=? ORDER BY created_at DESC'); $st->execute([current_user()['id']]); return $st->fetchAll(); }
    public function all(): array { return $this->db->query('SELECT * FROM orders ORDER BY created_at DESC')->fetchAll(); }
    public function updateStatus(int $id, string $status, ?string $notes): void { $extra=$status==='cancelled'?', cancelled_at=NOW()':($status==='delivered'?', delivered_at=NOW()':''); $this->db->prepare("UPDATE orders SET status=?, admin_notes=? $extra WHERE id=?")->execute([$status,$notes,$id]); }
    public function stats(): array { return ['revenue'=>(float)$this->db->query("SELECT COALESCE(SUM(total),0) FROM orders WHERE status IN('preparing','out_for_delivery','delivered')")->fetchColumn(),'orders'=>(int)$this->db->query('SELECT COUNT(*) FROM orders')->fetchColumn(),'pending'=>(int)$this->db->query("SELECT COUNT(*) FROM orders WHERE status IN('placed','preparing','out_for_delivery')")->fetchColumn(),'customers'=>(int)$this->db->query('SELECT COUNT(*) FROM users')->fetchColumn(),'low_stock'=>count((new Product())->lowStock())]; }
}
