<?php
class Product extends Model
{
    public function all(bool $activeOnly=false, ?int $categoryId=null, int $limit=0): array { $where=[];$p=[]; if($activeOnly)$where[]='p.is_active=1'; if($categoryId){$where[]='p.category_id=?';$p[]=$categoryId;} $sql='SELECT p.*,c.name_ar category_name,c.slug category_slug FROM products p JOIN categories c ON c.id=p.category_id'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY p.sort_order,p.name_ar'.($limit?' LIMIT '.(int)$limit:''); $st=$this->db->prepare($sql); $st->execute($p); return $st->fetchAll(); }
    public function findBySlug(string $slug): ?array { $st=$this->db->prepare('SELECT p.*,c.name_ar category_name,c.slug category_slug FROM products p JOIN categories c ON c.id=p.category_id WHERE p.slug=?'); $st->execute([$slug]); return $st->fetch() ?: null; }
    public function find(int $id): ?array { $st=$this->db->prepare('SELECT * FROM products WHERE id=?'); $st->execute([$id]); return $st->fetch() ?: null; }
    public function variants(int $pid, bool $activeOnly=false): array { $st=$this->db->prepare('SELECT * FROM product_variants WHERE product_id=?'.($activeOnly?' AND is_active=1':'').' ORDER BY sort_order,name_ar'); $st->execute([$pid]); return $st->fetchAll(); }
    public function save(array $d, ?int $id=null): int { $vals=[$d['category_id'],$d['name_ar'],$d['slug'],$d['description_ar'],$d['image_url'],$d['base_price'],$d['stock'],$d['is_weight_based'],$d['weight_options_grams'],$d['price_per_kg'],$d['unit_label_ar'],$d['is_active'],$d['sort_order']]; if($id){$st=$this->db->prepare('UPDATE products SET category_id=?,name_ar=?,slug=?,description_ar=?,image_url=?,base_price=?,stock=?,is_weight_based=?,weight_options_grams=?,price_per_kg=?,unit_label_ar=?,is_active=?,sort_order=? WHERE id=?'); $vals[]=$id; $st->execute($vals); return $id;} $st=$this->db->prepare('INSERT INTO products(category_id,name_ar,slug,description_ar,image_url,base_price,stock,is_weight_based,weight_options_grams,price_per_kg,unit_label_ar,is_active,sort_order) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)'); $st->execute($vals); return (int)$this->db->lastInsertId(); }
    public function saveVariants(int $pid, array $names, array $prices, array $stocks): void { $this->db->prepare('DELETE FROM product_variants WHERE product_id=?')->execute([$pid]); $st=$this->db->prepare('INSERT INTO product_variants(product_id,name_ar,price,stock,sort_order,is_active) VALUES(?,?,?,?,?,1)'); foreach($names as $i=>$n){ if(trim($n)==='') continue; $st->execute([$pid,trim($n),(float)($prices[$i]??0),(int)($stocks[$i]??0),$i]); } }
    public function delete(int $id): void { $this->db->prepare('DELETE FROM products WHERE id=?')->execute([$id]); }
    public function displayPrice(array $p, array $variants=[]): string { if($variants){$active=array_filter($variants,fn($v)=>$v['is_active']); if(!$active)return '—'; return 'يبدأ من '.money(min(array_column($active,'price')));} if($p['is_weight_based'] && $p['price_per_kg']!==null) return money($p['price_per_kg']).' / كجم'; return money($p['base_price']); }
    public function lowStock(): array { return $this->db->query('SELECT id,name_ar,stock,NULL variant_name FROM products WHERE stock<=5 AND is_active=1 UNION ALL SELECT p.id,p.name_ar,v.stock,v.name_ar FROM product_variants v JOIN products p ON p.id=v.product_id WHERE v.stock<=5 AND v.is_active=1 ORDER BY stock')->fetchAll(); }
}
